# Generated by Django 4.1.1 on 2022-11-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "nro_documento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("apellido", models.CharField(max_length=20, verbose_name="apellido")),
            ],
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=15, verbose_name="calle")),
                ("altura", models.IntegerField(verbose_name="altura")),
                (
                    "localidad",
                    models.CharField(max_length=20, verbose_name="localidad"),
                ),
                ("piso", models.IntegerField(max_length=30, verbose_name="piso")),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(max_length=30, verbose_name="descripcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imprenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15, verbose_name="nombre")),
                ("sitio_web", models.CharField(max_length=30, verbose_name="web")),
                ("email", models.CharField(max_length=20, verbose_name="email")),
                (
                    "id_domicilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="el_lector.domicilio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(max_length=30, verbose_name="descripcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(max_length=30, verbose_name="descripcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="apellido")),
                (
                    "id_domicilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="el_lector.domicilio",
                    ),
                ),
                (
                    "id_tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="el_lector.tipo_documento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("isbn", models.IntegerField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=30, verbose_name="titulo")),
                ("cant_paginas", models.IntegerField(verbose_name="paginas")),
                ("resena", models.CharField(max_length=100, verbose_name="resena")),
                (
                    "id_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="el_lector.autor",
                    ),
                ),
                (
                    "id_imprenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="el_lector.imprenta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="autor",
            name="id_pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="el_lector.pais"
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="id_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="el_lector.persona"
            ),
        ),
    ]
