# Generated by Django 3.2.12 on 2022-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=100, verbose_name='Codigo Barras')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
            ],
        ),
    ]
