# Generated by Django 4.1.1 on 2022-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("el_lector", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="domicilio",
            name="piso",
            field=models.IntegerField(verbose_name="piso"),
        )
    ]
