# Generated by Django 4.1.1 on 2022-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("el_lector", "0003_alter_imprenta_email")]

    operations = [
        migrations.AlterField(
            model_name="imprenta",
            name="sitio_web",
            field=models.URLField(max_length=40, verbose_name="web"),
        )
    ]
