# Generated by Django 4.1.1 on 2022-11-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("el_lector", "0004_alter_imprenta_sitio_web")]

    operations = [
        migrations.AlterField(
            model_name="domicilio",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="genero",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="imprenta",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pais",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="persona",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tipo_documento",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
